### PR TITLE
chore(dependencies): upgrade npm dependencies, migrate to npm @types

### PR DESCRIPTION
**Pull request by CoreyCole**

### CODE REVIEW

**Comment by CoreyCole** [comment]
Results from `npm outdated`
```
Package             Current  Wanted  Latest  Location
chai                  3.5.0   3.5.0   4.1.2  alexa-skills-kit-nodejs-lambda-boilerplate
coveralls            2.13.3  2.13.3   3.0.0  alexa-skills-kit-nodejs-lambda-boilerplate
dotenv                4.0.0   4.0.0   5.0.1  alexa-skills-kit-nodejs-lambda-boilerplate
fuse.js               2.7.4   2.7.4   3.2.0  alexa-skills-kit-nodejs-lambda-boilerplate
mocha                 3.5.3   3.5.3   5.1.1  alexa-skills-kit-nodejs-lambda-boilerplate
remap-istanbul        0.7.0   0.7.0  0.11.0  alexa-skills-kit-nodejs-lambda-boilerplate
sinon                1.17.7  1.17.7   4.5.0  alexa-skills-kit-nodejs-lambda-boilerplate
sinon-chai           2.14.0  2.14.0   3.0.0  alexa-skills-kit-nodejs-lambda-boilerplate
source-map-loader     0.1.6   0.1.6   0.2.3  alexa-skills-kit-nodejs-lambda-boilerplate
source-map-support   0.4.18  0.4.18   0.5.4  alexa-skills-kit-nodejs-lambda-boilerplate
ts-loader             2.3.7   2.3.7   4.2.0  alexa-skills-kit-nodejs-lambda-boilerplate
tslint                4.5.1   4.5.1   5.9.1  alexa-skills-kit-nodejs-lambda-boilerplate
webpack              1.15.0  1.15.0   4.6.0  alexa-skills-kit-nodejs-lambda-boilerplate
```

**Comment by CoreyCole** [comment]
Probably going to need to remove `typings install` from the build steps

**Comment by CoreyCole** [comment]
@michaelmyers is [this error](https://travis-ci.org/bespoken/alexa-skills-kit-nodejs-lambda-boilerplate/builds/369904517#L575) expected when the tests run? The `data[language]` property is undefined

Throwing in [WordlyHelloService](https://github.com/CoreyCole/alexa-skills-kit-nodejs-lambda-boilerplate/blob/master/src/services/WorldlyHello.ts) where I added a better error message to see what was going on.

**Comment by CoreyCole** [comment]
Nevermind, looks like yes:
```javascript
describe("with an unknown language", function () {
    let mockHandler = new MockHandler();
    mockHandler.event = { request: { intent: { slots: { Language: { value: "german" } } } } };
    let emitStub = sinon.stub(mockHandler, "emit");
    let worldlyHelloController = new WorldlyHelloController(mockHandler);
    worldlyHelloController.sayHello();
    it("returns hello world", function () {
        expect(emitStub).to.have.been.calledOnce;
        expect(emitStub).to.have.been.calledWith(":tell", "I could not find hello in that language");
    });
});
```

**Comment by CoreyCole** [comment]
In .travis.yml, I changed the cached directory to `$HOME/.npm` for node_module caching instead of node_module folder inside the project. This is suggested [here](https://stackoverflow.com/questions/42521884/should-i-have-travis-cache-node-modules-or-home-npm)

**Comment by CoreyCole** [comment]
@michaelmyers looks like the build is now passing! I'm now looking where I could add tests so the coverage doesn't go down

**Comment by CoreyCole** [comment]
right now the `npm run postinstall` is a blank script because I was getting build errors removing it. But, it is no longer necessary because there is no more need for `typings install`

**Comment by CoreyCole** [comment]
I also upgraded the ts/js compilation target to es6 when I was running into some "Promise" type vs. object problems

**Comment by CoreyCole** [comment]
I changed node version from 4 to 8.10 as lambda supports it https://docs.aws.amazon.com/lambda/latest/dg/current-supported-versions.html

**Comment by CoreyCole** [comment]
(tried closing and re-opening for coveralls to run again, didn't work 😕)

**Comment by CoreyCole** [comment]
Trying to use the latest webpack (4.6.0) running into some sourcemap problems. I'm going to need to learn more about how you guys had it setup previously and research how it works now. It looks like the new webpack has a [source-map-dev-tool-plugin](https://webpack.js.org/plugins/source-map-dev-tool-plugin/) built in, so we may be able to remove the banner plugin and just use that?

**Comment by CoreyCole** [comment]
In webpack, I removed json-loader because it was being run twice. I also modified the module.loaders/preloaders following the webpack 4 documentation.

@michaelmyers I'm not sure what the banner plugin is for, but I kept it in there. Do we have/need chunks for lambda functions?

**Comment by CoreyCole** [comment]
I also added `npm run build` as a travis step because I didn't know I had webpack problems until I ran it locally

**Comment by CoreyCole** [comment]
Okay sweet, I got webpack working in travis as well. Just waiting on coveralls now... 🤔

**Comment by CoreyCole** [comment]
@michaelmyers could you review when you get a chance?

**Comment by CoreyCole** [comment]
alexa/ask sdk V2 is coming soon, so I will update this fork again once that comes out. We may want to wait to merge this until after then~

**Comment by jkelvie** [comment]
Hi @CoreyCole - thank you for the pull request! Great stuff.

**Pull request merged**
